### ISSUE TITLE
실행 오류 (Help)

### ISSUE THREAD

**Issue by csc7545** [Global-Handong-Oriented-Security-Team/Automated-Lecture-Assessment#3]
python main.py 실행 후 계정 입력시 발생
외않됨?

`Traceback (most recent call last):
  File "/Users/choeseongchan/Desktop/Automated-Lecture-Assessment/main.py", line 17, in <module>
    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/webdriver_manager/chrome.py", line 39, in install
    driver_path = self._get_driver_path(self.driver)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/webdriver_manager/core/manager.py", line 30, in _get_driver_path
    file = self._download_manager.download_file(driver.get_url())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/webdriver_manager/core/download_manager.py", line 28, in download_file
    response = self._http_client.get(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/webdriver_manager/core/http.py", line 33, in get
    self.validate_response(resp)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/webdriver_manager/core/http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/120.0.6099/chromedriver_mac64.zip
`

**Comment by jiniljeil** [comment]
크롬 드라이버가 실행이 안된 것 같은데 ... 이제 봄..
